### PR TITLE
Add Qos Policy tests

### PR DESCRIPTION
**Pull request by smazurov**
Added some http req mocking so we can be sure marshaling/unmarshalling works correctly. I added a travis file as well, but its up to you guys to modify it to do what you want it to do.

Also:

- reordered methods to better fit CRUD in `qos-policy`
- made all `VolumeSpaceAtrributes` fields `omitempty`
- added some early http error transformation
- added editorconfig file for xml files.

Note: im using a [diff library](https://github.com/andreyvit/diff) to better show xml file differences, so in order to run tests you need to do `go get -t ./netapp`

### CODE REVIEW

**Comment by smazurov** [comment]
didn't mean to close this

**Comment by pyama86** [comment]
This is the great PR. Thank you.

**Comment by smazurov** [comment]
do you want to enable travis on the main repo?

**Comment by pyama86** [comment]
> do you want to enable travis on the main repo?

I kept it enabled! Thank you.

**Pull request merged**
